# Task
- apply Dot-product Multiplication

In [1]:
import numpy as np

In [2]:
def vector_dot(v1,v2):
    assert len(v1) == len(v2), "Vectors must be the same size"
    
    scalar_sum = sum([a*b for a,b in zip(v1,v2)])
    return scalar_sum

In [3]:
def get_vec_list(mat1,mat2):
    vec1_list = [mat1[r1] for r1 in range(len(mat1))]
    vec2_list = [[mat2[r][c] for r in range(len(mat2))] for c in range(len(mat2[0]))]
    
    return vec1_list,vec2_list

In [4]:
def matrix_dot(m1,m2):
    assert len(m1[0]) == len(m2), "Number of columns of 1st matrix must equal number of rows of second matrix"
    
    vec1_list,vec2_list = get_vec_list(m1,m2)   
    
    result = [[vector_dot(v1,v2) for v2 in vec2_list] for v1 in vec1_list]
    
    return result

### Example 1

In [5]:
mat1 = [[2,1,3],
       [2,4,4]]

mat2 = [[1,4,1],
       [2,3,8],
       [1,6,2]]

matrix_dot(mat1,mat2)

[[7, 29, 16], [14, 44, 42]]

In [6]:
# Check result with result from numpy
m1 = np.array(mat1)
m2 = np.array(mat2)

print(m1.dot(m2))

[[ 7 29 16]
 [14 44 42]]


### Example 2

In [7]:
mat1 = [[1,2],
       [2,3]]

mat2 = [[2,1],
       [2,4]]

matrix_dot(mat1,mat2)

[[6, 9], [10, 14]]

In [8]:
# Check result with result from numpy
m1 = np.array(mat1)
m2 = np.array(mat2)

print(m1.dot(m2))

[[ 6  9]
 [10 14]]
